-- meta_insights: daily snapshot of Meta Ads performance
create table if not exists public.meta_insights (
  id            bigint generated by default as identity primary key,
  date          date not null,
  campaign_id   text not null,
  campaign_name text,
  adset_id      text not null,
  adset_name    text,
  ad_id         text not null,
  ad_name       text,
  spend         numeric(10,2),
  impressions   integer,
  clicks        integer,
  reach         integer,
  synced_at     timestamp with time zone default now(),
  unique (date, campaign_id, adset_id, ad_id)
);

-- hubspot_contacts: enriched contacts matched by phone
create table if not exists public.hubspot_contacts (
  id              bigint generated by default as identity primary key,
  phone           text not null unique,
  hs_contact_id   text,
  lifecycle_stage text,
  deal_value      numeric(10,2),
  deal_stage      text,
  updated_at      timestamp with time zone default now()
);

-- sync_logs: record of all sync operations
create table if not exists public.sync_logs (
  id              bigint generated by default as identity primary key,
  type            text not null check (type in ('meta', 'hubspot', 'action')),
  status          text not null check (status in ('success', 'error')),
  message         text,
  records_synced  integer,
  created_at      timestamp with time zone default now()
);

-- RLS policies
alter table public.meta_insights enable row level security;
alter table public.hubspot_contacts enable row level security;
alter table public.sync_logs enable row level security;

-- Only authenticated users can read
create policy "Authenticated read meta_insights"
  on public.meta_insights for select
  to authenticated using (true);

create policy "Authenticated read hubspot_contacts"
  on public.hubspot_contacts for select
  to authenticated using (true);

create policy "Authenticated read sync_logs"
  on public.sync_logs for select
  to authenticated using (true);

-- Service role can write (used by API routes with service key)
create policy "Service role write meta_insights"
  on public.meta_insights for all
  to service_role using (true);

create policy "Service role write hubspot_contacts"
  on public.hubspot_contacts for all
  to service_role using (true);

create policy "Service role write sync_logs"
  on public.sync_logs for all
  to service_role using (true);
