-- Call history synced from HubSpot (one row per call engagement), so calls
-- can be filtered by period and charted daily, same as WhatsApp messages.
create table if not exists public.hubspot_calls (
  id            bigint generated by default as identity primary key,
  hs_call_id    text not null unique,
  phone         text not null,
  owner_id      text,
  owner_name    text,
  call_at       timestamptz not null,
  direction     text,
  disposition   text,
  synced_at     timestamptz not null default now()
);

create index if not exists hubspot_calls_phone_idx on public.hubspot_calls (phone);
create index if not exists hubspot_calls_call_at_idx on public.hubspot_calls (call_at);

alter table public.hubspot_calls enable row level security;

create policy "Authenticated read hubspot_calls"
  on public.hubspot_calls for select
  to authenticated using (true);

create policy "Service role write hubspot_calls"
  on public.hubspot_calls for all
  to service_role using (true);
